#version: "3.9"

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_node1
    volumes:
      - ./config/node1.toml:/app/config.toml:ro
      - ./data/node1:/app/chain.db
    ports:
      - "4001:4001"     # internal blockchain port
      - "3001:3000"     # API (Axum) endpoint
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/chain"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust_node2
    volumes:
      - ./config/node2.toml:/app/config.toml:ro
      - ./data/node2:/app/chain.db
    ports:
      - "4002:4001"
      - "3002:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/chain"]
      interval: 10s
      timeout: 3s
      retries: 3
    restart: unless-stopped
